// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJBdvKjNF8N5kCHus27nXywE81HD1MVM',
    appId: '1:540766455702:web:7d60e9d2511d043570bfb7',
    messagingSenderId: '540766455702',
    projectId: 'clonesender-afea3',
    authDomain: 'clonesender-afea3.firebaseapp.com',
    storageBucket: 'clonesender-afea3.appspot.com',
    measurementId: 'G-W5BVMEH301',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcVwDjSIW-Sb8ZJGj2r9hgKiw6Cf5WXY',
    appId: '1:540766455702:android:32ed2877625885f870bfb7',
    messagingSenderId: '540766455702',
    projectId: 'clonesender-afea3',
    storageBucket: 'clonesender-afea3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASitiO1OS_mQwKSF98mNygMbKwC7XWtk8',
    appId: '1:540766455702:ios:4f49f7cf6c2e035a70bfb7',
    messagingSenderId: '540766455702',
    projectId: 'clonesender-afea3',
    storageBucket: 'clonesender-afea3.appspot.com',
    iosClientId: '540766455702-sks3vssiqe8s0di3usbgkjkk07cucvm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASitiO1OS_mQwKSF98mNygMbKwC7XWtk8',
    appId: '1:540766455702:ios:4f49f7cf6c2e035a70bfb7',
    messagingSenderId: '540766455702',
    projectId: 'clonesender-afea3',
    storageBucket: 'clonesender-afea3.appspot.com',
    iosClientId: '540766455702-sks3vssiqe8s0di3usbgkjkk07cucvm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.message',
  );
}
